# Generated by Django 5.0.3 on 2024-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actresses',
            name='name_rus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actresses',
            name='surname_rus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='actresses',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='actresses',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actresses',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='actresses',
            name='sign_zodiac',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='actresses',
            name='surname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
