# Generated by Django 5.0.3 on 2024-07-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0002_actresses_name_rus_actresses_surname_rus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actresses',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actresses',
            name='city_of_birth',
        ),
        migrations.RemoveField(
            model_name='actresses',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='actresses',
            name='sign_zodiac',
        ),
        migrations.RemoveField(
            model_name='actresses',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='actresses',
            name='surname_rus',
        ),
    ]
