# Generated by Django 5.0.3 on 2024-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0003_remove_actresses_age_remove_actresses_city_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actresses',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actresses',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='actresses',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actresses',
            name='sign_zodiac',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='actresses',
            name='surname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='actresses',
            name='surname_rus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
