# Generated by Django 5.0.3 on 2024-07-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0005_actor_delete_actresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('name_rus', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(blank=True, max_length=15, null=True)),
                ('surname_rus', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sign_zodiac', models.CharField(blank=True, max_length=15, null=True)),
                ('city_of_birth', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
