# Generated by Django 5.0.3 on 2024-07-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0006_actresses_delete_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actresses',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
