# Generated by Django 5.0.3 on 2024-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0007_actresses_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actresses',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
