# Generated by Django 5.0.3 on 2024-07-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0008_alter_actresses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actresses',
            name='name_rus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
