# Generated by Django 5.0.3 on 2024-07-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0009_alter_actresses_name_rus'),
    ]

    operations = [
        migrations.AddField(
            model_name='actresses',
            name='image',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
