# Generated by Django 5.0.3 on 2024-07-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0012_alter_actresses_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actresses',
            name='image',
        ),
    ]
