# Generated by Django 5.0.3 on 2024-07-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_100_actresses', '0013_remove_actresses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='actresses',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
